### ISSUE TITLE
App user dashboard template creation in flutter

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-client#10]
<img width="808" alt="image" src="https://github.com/eronka/culero-client/assets/4149765/3a17477d-a986-4e24-92f6-e6fce8de3d1d">

Logged in page to be created in flutter..

We will need side drawer / mobile navigation and the card components in the dashboard. In Figma, it shows other pages we will have to build, please build the dashboard elements scalable and reusable throughout other pages

https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4/Culero?type=design&node-id=0%3A1&mode=design&t=SpG65QyGaCJhV57S-1

**Comment by syedbarimanjan** [comment]
/attempt #10

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clv8zt6h4000nl20cz2wx36i0/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by syedbarimanjan** [comment]
@hsb1007 can you approve the figma file access. and assign the issue to me. and can you explian what is this project about(not just this issue all of the project)

**Comment by hsb1007** [comment]
> @hsb1007 can you approve the figma file access. and assign the issue to me. and can you explian what is this project about(not just this issue all of the project)

Approved!

**Comment by syedbarimanjan** [comment]
> > @hsb1007 can you approve the figma file access. and assign the issue to me. and can you explian what is this project about(not just this issue all of the project)
> 
> Approved!

you want these two elements to be made
![Screenshot from 2024-04-21 09-37-31](https://github.com/eronka/culero-client/assets/112156147/6ebabeb1-c0ff-4ce6-8e5e-9cc4a490366c)
![Screenshot from 2024-04-21 09-37-20](https://github.com/eronka/culero-client/assets/112156147/87964420-a705-49c2-b567-a1f29ee50347)

ps:can you provide the discord link, assign the issue and explain about the project

**Comment by hsb1007** [comment]
Here we go

https://discord.gg/uJcftT3x

**Comment by hsb1007** [comment]
> > > @hsb1007 can you approve the figma file access. and assign the issue to me. and can you explian what is this project about(not just this issue all of the project)
> > 
> > 
> > Approved!
> 
> you want these two elements to be made ![Screenshot from 2024-04-21 09-37-31](https://private-user-images.githubusercontent.com/112156147/324223631-6ebabeb1-c0ff-4ce6-8e5e-9cc4a490366c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU0NDAsIm5iZiI6MTcxMzY3NTE0MCwicGF0aCI6Ii8xMTIxNTYxNDcvMzI0MjIzNjMxLTZlYmFiZWIxLWMwZmYtNGNlNi04ZTVlLTljYzRhNDkwMzY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWE1MWMzZTdjMzNmMzI2Y2YxYzgyOTExZjNlZTg4MjRkNzUyODNmYzQxOTJjN2E3YmE1MGJmY2QzMmZhYTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1FVkwAlQwEct_gk1_Q3LmlI0UVH6ioVWoIEfLTB47Gg) ![Screenshot from 2024-04-21 09-37-20](https://private-user-images.githubusercontent.com/112156147/324223635-87964420-a705-49c2-b567-a1f29ee50347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU0NDAsIm5iZiI6MTcxMzY3NTE0MCwicGF0aCI6Ii8xMTIxNTYxNDcvMzI0MjIzNjM1LTg3OTY0NDIwLWE3MDUtNDljMi1iNTY3LWExZjI5ZWU1MDM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzM3ZDgyNGE1NTIyZTc3ZDMwNjNjN2Y5ZjllN2M2ZmIwMTYzOTQ3NTliOGU0NDg1MjA5MzY4ODg2ZjEwYTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jJHhfI-wDvwhe-dN1nHnjWLUUBEA_PauLW1icxy1sIw)
> 
> ps:can you provide the discord link, assign the issue and explain about the project

And these elements too and put them into the dashboard page!

<img width="475" alt="image" src="https://github.com/eronka/culero-client/assets/4149765/47545ad2-6bef-4a40-95e5-adeb98b06bef">



README has been updated! it only existed in culero-api repo but I have copied over! Thank you for pointing out!

**Comment by syedbarimanjan** [comment]
> > > > @hsb1007 can you approve the figma file access. and assign the issue to me. and can you explian what is this project about(not just this issue all of the project)
> > > 
> > > 
> > > Approved!
> > 
> > 
> > you want these two elements to be made ![Screenshot from 2024-04-21 09-37-31](https://private-user-images.githubusercontent.com/112156147/324223631-6ebabeb1-c0ff-4ce6-8e5e-9cc4a490366c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU0NDAsIm5iZiI6MTcxMzY3NTE0MCwicGF0aCI6Ii8xMTIxNTYxNDcvMzI0MjIzNjMxLTZlYmFiZWIxLWMwZmYtNGNlNi04ZTVlLTljYzRhNDkwMzY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWE1MWMzZTdjMzNmMzI2Y2YxYzgyOTExZjNlZTg4MjRkNzUyODNmYzQxOTJjN2E3YmE1MGJmY2QzMmZhYTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1FVkwAlQwEct_gk1_Q3LmlI0UVH6ioVWoIEfLTB47Gg) ![Screenshot from 2024-04-21 09-37-20](https://private-user-images.githubusercontent.com/112156147/324223635-87964420-a705-49c2-b567-a1f29ee50347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU0NDAsIm5iZiI6MTcxMzY3NTE0MCwicGF0aCI6Ii8xMTIxNTYxNDcvMzI0MjIzNjM1LTg3OTY0NDIwLWE3MDUtNDljMi1iNTY3LWExZjI5ZWU1MDM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzM3ZDgyNGE1NTIyZTc3ZDMwNjNjN2Y5ZjllN2M2ZmIwMTYzOTQ3NTliOGU0NDg1MjA5MzY4ODg2ZjEwYTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jJHhfI-wDvwhe-dN1nHnjWLUUBEA_PauLW1icxy1sIw)
> > ps:can you provide the discord link, assign the issue and explain about the project
> 
> And these elements too and put them into the dashboard page!
> 
> <img alt="image" width="475" src="https://private-user-images.githubusercontent.com/4149765/324224187-47545ad2-6bef-4a40-95e5-adeb98b06bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU1MTIsIm5iZiI6MTcxMzY3NTIxMiwicGF0aCI6Ii80MTQ5NzY1LzMyNDIyNDE4Ny00NzU0NWFkMi02YmVmLTRhNDAtOTVlNS1hZGViOThiMDZiZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMDQ1MzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTllMzE5ODFkZDRkYTEwNWMxOTY5NTg0NWE5Njg0ODhlNWFjZjYzNTE5Nzk5NWQ3ZDI1OWMyYTI1ZTIyZDM0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jY0LRAM3REbolf4GODkXlph5YUhLVYPIuBnt-xRg534">
> README has been updated! it only existed in culero-api repo but I have copied over! Thank you for pointing out!

so you want all of the dashboard page to be built and the sidebar too. does it have to be mobile responsive too like in the design?

ps: assign the issue so other contributors know that someone is working on it.

**Comment by hsb1007** [comment]
> > > > > @hsb1007 can you approve the figma file access. and assign the issue to me. and can you explian what is this project about(not just this issue all of the project)
> > > > 
> > > > 
> > > > Approved!
> > > 
> > > 
> > > you want these two elements to be made ![Screenshot from 2024-04-21 09-37-31](https://private-user-images.githubusercontent.com/112156147/324223631-6ebabeb1-c0ff-4ce6-8e5e-9cc4a490366c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU0NDAsIm5iZiI6MTcxMzY3NTE0MCwicGF0aCI6Ii8xMTIxNTYxNDcvMzI0MjIzNjMxLTZlYmFiZWIxLWMwZmYtNGNlNi04ZTVlLTljYzRhNDkwMzY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWE1MWMzZTdjMzNmMzI2Y2YxYzgyOTExZjNlZTg4MjRkNzUyODNmYzQxOTJjN2E3YmE1MGJmY2QzMmZhYTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1FVkwAlQwEct_gk1_Q3LmlI0UVH6ioVWoIEfLTB47Gg) ![Screenshot from 2024-04-21 09-37-20](https://private-user-images.githubusercontent.com/112156147/324223635-87964420-a705-49c2-b567-a1f29ee50347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU0NDAsIm5iZiI6MTcxMzY3NTE0MCwicGF0aCI6Ii8xMTIxNTYxNDcvMzI0MjIzNjM1LTg3OTY0NDIwLWE3MDUtNDljMi1iNTY3LWExZjI5ZWU1MDM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzM3ZDgyNGE1NTIyZTc3ZDMwNjNjN2Y5ZjllN2M2ZmIwMTYzOTQ3NTliOGU0NDg1MjA5MzY4ODg2ZjEwYTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jJHhfI-wDvwhe-dN1nHnjWLUUBEA_PauLW1icxy1sIw)
> > > ps:can you provide the discord link, assign the issue and explain about the project
> > 
> > 
> > And these elements too and put them into the dashboard page!
> > <img alt="image" width="475" src="https://private-user-images.githubusercontent.com/4149765/324224187-47545ad2-6bef-4a40-95e5-adeb98b06bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU1MTIsIm5iZiI6MTcxMzY3NTIxMiwicGF0aCI6Ii80MTQ5NzY1LzMyNDIyNDE4Ny00NzU0NWFkMi02YmVmLTRhNDAtOTVlNS1hZGViOThiMDZiZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMDQ1MzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTllMzE5ODFkZDRkYTEwNWMxOTY5NTg0NWE5Njg0ODhlNWFjZjYzNTE5Nzk5NWQ3ZDI1OWMyYTI1ZTIyZDM0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jY0LRAM3REbolf4GODkXlph5YUhLVYPIuBnt-xRg534">
> > README has been updated! it only existed in culero-api repo but I have copied over! Thank you for pointing out!
> 
> so you want all of the dashboard page to be built and the sidebar too. does it have to be mobile responsive too like in the design?
> 
> ps: assign the issue so other contributors know that someone is working on it.

Yes we do need it to be mobile responsive! 

Do you want me to assign this to you?

**Comment by syedbarimanjan** [comment]
> > > > > > @hsb1007 can you approve the figma file access. and assign the issue to me. and can you explian what is this project about(not just this issue all of the project)
> > > > > 
> > > > > 
> > > > > Approved!
> > > > 
> > > > 
> > > > you want these two elements to be made ![Screenshot from 2024-04-21 09-37-31](https://private-user-images.githubusercontent.com/112156147/324223631-6ebabeb1-c0ff-4ce6-8e5e-9cc4a490366c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU0NDAsIm5iZiI6MTcxMzY3NTE0MCwicGF0aCI6Ii8xMTIxNTYxNDcvMzI0MjIzNjMxLTZlYmFiZWIxLWMwZmYtNGNlNi04ZTVlLTljYzRhNDkwMzY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWE1MWMzZTdjMzNmMzI2Y2YxYzgyOTExZjNlZTg4MjRkNzUyODNmYzQxOTJjN2E3YmE1MGJmY2QzMmZhYTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1FVkwAlQwEct_gk1_Q3LmlI0UVH6ioVWoIEfLTB47Gg) ![Screenshot from 2024-04-21 09-37-20](https://private-user-images.githubusercontent.com/112156147/324223635-87964420-a705-49c2-b567-a1f29ee50347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU0NDAsIm5iZiI6MTcxMzY3NTE0MCwicGF0aCI6Ii8xMTIxNTYxNDcvMzI0MjIzNjM1LTg3OTY0NDIwLWE3MDUtNDljMi1iNTY3LWExZjI5ZWU1MDM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNDUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzM3ZDgyNGE1NTIyZTc3ZDMwNjNjN2Y5ZjllN2M2ZmIwMTYzOTQ3NTliOGU0NDg1MjA5MzY4ODg2ZjEwYTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jJHhfI-wDvwhe-dN1nHnjWLUUBEA_PauLW1icxy1sIw)
> > > > ps:can you provide the discord link, assign the issue and explain about the project
> > > 
> > > 
> > > And these elements too and put them into the dashboard page!
> > > <img alt="image" width="475" src="https://private-user-images.githubusercontent.com/4149765/324224187-47545ad2-6bef-4a40-95e5-adeb98b06bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzU1MTIsIm5iZiI6MTcxMzY3NTIxMiwicGF0aCI6Ii80MTQ5NzY1LzMyNDIyNDE4Ny00NzU0NWFkMi02YmVmLTRhNDAtOTVlNS1hZGViOThiMDZiZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMDQ1MzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTllMzE5ODFkZDRkYTEwNWMxOTY5NTg0NWE5Njg0ODhlNWFjZjYzNTE5Nzk5NWQ3ZDI1OWMyYTI1ZTIyZDM0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jY0LRAM3REbolf4GODkXlph5YUhLVYPIuBnt-xRg534">
> > > README has been updated! it only existed in culero-api repo but I have copied over! Thank you for pointing out!
> > 
> > 
> > so you want all of the dashboard page to be built and the sidebar too. does it have to be mobile responsive too like in the design?
> > ps: assign the issue so other contributors know that someone is working on it.
> 
> Yes we do need it to be mobile responsive!
> 
> Do you want me to assign this to you?

yes I will work on this
