### ISSUE TITLE
Flutter deployment and set up CI/CD process and guideline documentation

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-client#11]
Flutter deployment and set up CI/CD process and guideline documentation.

Firebase will be our hosting and will need help setting up ci /cd for flutter app deployment

**Comment by Bhavyajain21** [comment]
/attempt #11

I would like to give it a try, can I be assigned? @hsb1007 

<div id="algora" />

| [Algora profile](https://console.algora.io/@/Bhavyajain21) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Bhavyajain21 | &nbsp;&nbsp;&nbsp;4 eronka bounties <br/> + 2 bounties from 1 project | <div align="center">Rust, TypeScript, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clv900qkc0008mj0d0y79hszc/cancel-attempt) |

**Comment by hsb1007** [comment]
Welcome back =) I have assigned to you

**Comment by Bhavyajain21** [comment]
Great, Thank you!
