### ISSUE TITLE
Flutter to have general structure to do API call and connect user registration / login API to current project

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-client#12]
Flutter to have general structure to do API call and connect user registration / login API to current project

**Comment by ghost** [comment]
/attempt #12
Could I get assigned?

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clv90wfzt0006l10cnrvi5s1v/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Bhavyajain21** [comment]
Can I be assigned? @hsb1007

**Comment by hsb1007** [comment]
> /attempt #12 Could I get assigned?
> 
> Options
> * [
>           Cancel my attempt
>         ](https://console.algora.io/api/bounties/clv90wfzt0006l10cnrvi5s1v/cancel-attempt)

Hi @joshauh46 , This is going to be assigned to @bhavyajain21 as per the conversation we are having via Discord!

You are welcome to join our discord, we have a lot of work to do and we need more Flutter expertise!
