### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-client#6]

**Comment by hsb1007** [comment]
For Rutik to complete the work, please do not attempt

**Comment by rutikthakre** [comment]
/attempt #6

<div id="algora" />

| [Algora profile](https://console.algora.io/@/Rutik7066) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Rutik7066 | &nbsp;&nbsp;&nbsp;1 eronka bounty <br/> + 6 bounties from 5 projects | <div align="center">Go, Rust, <br />Python & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clv6dq02c000lmg0c9sso8qa4/cancel-attempt) |

**Comment by rutikthakre** [comment]
Hi @hsb1007 PR is ready to merge.
