### ISSUE TITLE
Flutter setup

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-client#7]

**Comment by rutikthakre** [comment]
@hsb1007  Ready to work.

**Comment by rutikthakre** [comment]
this will not work.

**Comment by rutikthakre** [comment]
try /tip $600 @Rutik7066

**Comment by rutikthakre** [comment]
/attempt #7

<div id="algora" />

| [Algora profile](https://console.algora.io/@/Rutik7066) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Rutik7066 | 6 bounties from 5 projects | <div align="center">Go, Rust, <br />Python & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clv6diezn000alh0cdaon3uze/cancel-attempt) |

**Comment by rutikthakre** [comment]
Thank you so much @hsb1007 😊
